forlms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('',include('lms.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/profile/', include('authentication.urls')),
    path('q/', include('quiz.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

lms/urls.py
from django.urls import path
from lms.views import index,about,blog,contact,event,cart,checkout,detail,onended,qna,allcourses,mycourses,\
CourseDetail,enrol,answer,timer
from authentication.views import profile

app_name = 'lms'

urlpatterns = [
    path('',index,name = 'index'),
    path('about/',about,name = 'about'),
    path('course/<slug:slug>/',CourseDetail.as_view(),name = 'coursedetail'),
    path('allcourses/',allcourses,name = 'allcourses'),
    path('qna/<slug:slug>/',qna,name = 'qna'),
    path('answer/<slug:slug>/<int:pk>/',answer,name = 'answer'),
    path('mycourses/',mycourses,name = 'mycourses'),
    path('blog/',blog,name = 'blog'),
    path('contact/',contact,name = 'contact'),
    path('event/',event,name = 'event'),
    path('cart/',cart,name = 'cart'),
    path('checkout/<slug:slug>/',checkout,name = 'checkout'),
    path('detail/<slug:slug>/',detail.as_view(),name = 'detail'),
    path('ajax/onended/',onended,name = 'onended'),
    path('ajax/staus/',enrol,name = 'status'),
    path('timer/',timer,name = 'timer'),
]

quiz/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import re_path as url

from .views import QuizListView, CategoriesListView, \
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList, \
    QuizMarkingDetail, QuizDetailView, QuizTake

urlpatterns = [

    url(r'^$',
        view=QuizListView.as_view(),
        name='quiz_index'),

    url(r'^category/$',
        view=CategoriesListView.as_view(),
        name='quiz_category_list_all'),

    url(r'^category/(?P<category_name>[\w|\W-]+)/$',
        view=ViewQuizListByCategory.as_view(),
        name='quiz_category_list_matching'),

    url(r'^progress/$',
        view=QuizUserProgressView.as_view(),
        name='quiz_progress'),

    url(r'^marking/$',
        view=QuizMarkingList.as_view(),
        name='quiz_marking'),

    url(r'^marking/(?P<pk>[\d.]+)/$',
        view=QuizMarkingDetail.as_view(),
        name='quiz_marking_detail'),

    #  passes variable 'quiz_name' to quiz_take view
    url(r'^(?P<slug>[\w-]+)/$',
        view=QuizDetailView.as_view(),
        name='quiz_start_page'),

    url(r'^(?P<quiz_name>[\w-]+)/take/$',
        view=QuizTake.as_view(),
        name='quiz_question'),
]

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list,
                                                   widget=RadioSelect)


class EssayForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))

quiz/views.py
import random

from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, render
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, TemplateView, FormView

from .forms import QuestionForm, EssayForm
from .models import Quiz, Category, Progress, Sitting, Question
from essay.models import Essay_Question


class QuizMarkerMixin(object):
    @method_decorator(login_required)
    @method_decorator(permission_required('quiz.view_sittings'))
    def dispatch(self, *args, **kwargs):
        return super(QuizMarkerMixin, self).dispatch(*args, **kwargs)


class SittingFilterTitleMixin(object):
    def get_queryset(self):
        queryset = super(SittingFilterTitleMixin, self).get_queryset()
        quiz_filter = self.request.GET.get('quiz_filter')
        if quiz_filter:
            queryset = queryset.filter(quiz__title__icontains=quiz_filter)

        return queryset


class QuizListView(ListView):
    model = Quiz

    def get_queryset(self):
        queryset = super(QuizListView, self).get_queryset()
        return queryset.filter(draft=False)


class QuizDetailView(DetailView):
    model = Quiz
    slug_field = 'url'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CategoriesListView(ListView):
    model = Category


class ViewQuizListByCategory(ListView):
    model = Quiz
    template_name = 'view_quiz_category.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            category=self.kwargs['category_name']
        )

        return super(ViewQuizListByCategory, self).\
            dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewQuizListByCategory, self)\
            .get_context_data(**kwargs)

        context['category'] = self.category
        return context

    def get_queryset(self):
        queryset = super(ViewQuizListByCategory, self).get_queryset()
        return queryset.filter(category=self.category, draft=False)


class QuizUserProgressView(TemplateView):
    template_name = 'progress.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(QuizUserProgressView, self)\
            .dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(QuizUserProgressView, self).get_context_data(**kwargs)
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        context['cat_scores'] = progress.list_all_cat_scores
        context['exams'] = progress.show_exams()
        return context


class QuizMarkingList(QuizMarkerMixin, SittingFilterTitleMixin, ListView):
    model = Sitting

    def get_queryset(self):
        queryset = super(QuizMarkingList, self).get_queryset()\
                                               .filter(complete=True)

        user_filter = self.request.GET.get('user_filter')
        if user_filter:
            queryset = queryset.filter(user__username__icontains=user_filter)

        return queryset


class QuizMarkingDetail(QuizMarkerMixin, DetailView):
    model = Sitting

    def post(self, request, *args, **kwargs):
        sitting = self.get_object()

        q_to_toggle = request.POST.get('qid', None)
        if q_to_toggle:
            q = Question.objects.get_subclass(id=int(q_to_toggle))
            if int(q_to_toggle) in sitting.get_incorrect_questions:
                sitting.remove_incorrect_question(q)
            else:
                sitting.add_incorrect_question(q)

        return self.get(request)

    def get_context_data(self, **kwargs):
        context = super(QuizMarkingDetail, self).get_context_data(**kwargs)
        context['questions'] =\
            context['sitting'].get_questions(with_answers=True)
        return context


class QuizTake(FormView):
    form_class = QuestionForm
    template_name = 'question.html'
    result_template_name = 'result.html'
    single_complete_template_name = 'single_complete.html'

    def dispatch(self, request, *args, **kwargs):
        self.quiz = get_object_or_404(Quiz, url=self.kwargs['quiz_name'])
        if self.quiz.draft and not request.user.has_perm('quiz.change_quiz'):
            raise PermissionDenied

        try:
            self.logged_in_user = self.request.user.is_authenticated()
        except TypeError:
            self.logged_in_user = self.request.user.is_authenticated

        if self.logged_in_user:
            self.sitting = Sitting.objects.user_sitting(request.user,
                                                        self.quiz)
        else:
            self.sitting = self.anon_load_sitting()

        if self.sitting is False:
            return render(request, self.single_complete_template_name)

        return super(QuizTake, self).dispatch(request, *args, **kwargs)

    def get_form(self, *args, **kwargs):
        if self.logged_in_user:
            self.question = self.sitting.get_first_question()
            self.progress = self.sitting.progress()
        else:
            self.question = self.anon_next_question()
            self.progress = self.anon_sitting_progress()

        if self.question.__class__ is Essay_Question:
            form_class = EssayForm
        else:
            form_class = self.form_class

        return form_class(**self.get_form_kwargs())

    def get_form_kwargs(self):
        kwargs = super(QuizTake, self).get_form_kwargs()

        return dict(kwargs, question=self.question)

    def form_valid(self, form):
        if self.logged_in_user:
            self.form_valid_user(form)
            if self.sitting.get_first_question() is False:
                return self.final_result_user()
        else:
            self.form_valid_anon(form)
            if not self.request.session[self.quiz.anon_q_list()]:
                return self.final_result_anon()

        self.request.POST = {}

        return super(QuizTake, self).get(self, self.request)

    def get_context_data(self, **kwargs):
        context = super(QuizTake, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['quiz'] = self.quiz
        if hasattr(self, 'previous'):
            context['previous'] = self.previous
        if hasattr(self, 'progress'):
            context['progress'] = self.progress
        return context

    def form_valid_user(self, form):
        progress, c = Progress.objects.get_or_create(user=self.request.user)
        guess = form.cleaned_data['answers']
        is_correct = self.question.check_if_correct(guess)

        if is_correct is True:
            self.sitting.add_to_score(1)
            progress.update_score(self.question, 1, 1)
        else:
            self.sitting.add_incorrect_question(self.question)
            progress.update_score(self.question, 0, 1)

        if self.quiz.answers_at_end is not True:
            self.previous = {'previous_answer': guess,
                             'previous_outcome': is_correct,
                             'previous_question': self.question,
                             'answers': self.question.get_answers(),
                             'question_type': {self.question
                                               .__class__.__name__: True}}
        else:
            self.previous = {}

        self.sitting.add_user_answer(self.question, guess)
        self.sitting.remove_first_question()

    def final_result_user(self):
        results = {
            'quiz': self.quiz,
            'score': self.sitting.get_current_score,
            'max_score': self.sitting.get_max_score,
            'percent': self.sitting.get_percent_correct,
            'sitting': self.sitting,
            'previous': self.previous,
        }

        self.sitting.mark_quiz_complete()

        if self.quiz.answers_at_end:
            results['questions'] =\
                self.sitting.get_questions(with_answers=True)
            results['incorrect_questions'] =\
                self.sitting.get_incorrect_questions

        if self.quiz.exam_paper is False:
            self.sitting.delete()

        return render(self.request, self.result_template_name, results)

    def anon_load_sitting(self):
        if self.quiz.single_attempt is True:
            return False

        if self.quiz.anon_q_list() in self.request.session:
            return self.request.session[self.quiz.anon_q_list()]
        else:
            return self.new_anon_quiz_session()

    def new_anon_quiz_session(self):
        """
        Sets the session variables when starting a quiz for the first time
        as a non signed-in user
        """
        self.request.session.set_expiry(259200)  # expires after 3 days
        questions = self.quiz.get_questions()
        question_list = [question.id for question in questions]

        if self.quiz.random_order is True:
            random.shuffle(question_list)

        if self.quiz.max_questions and (self.quiz.max_questions
                                        < len(question_list)):
            question_list = question_list[:self.quiz.max_questions]

        # session score for anon users
        self.request.session[self.quiz.anon_score_id()] = 0

        # session list of questions
        self.request.session[self.quiz.anon_q_list()] = question_list

        # session list of question order and incorrect questions
        self.request.session[self.quiz.anon_q_data()] = dict(
            incorrect_questions=[],
            order=question_list,
        )

quiz/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
<meta charset="utf-8">

<title>{% trans "Example Quiz Website" %} | {% block title %}{% endblock %}</title>
<meta name="description" content="{% block description %}{% endblock %}">

<!-- styles -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>


<!-- Before the quiz content -->



{% block content %}

{% endblock %}



<!-- After the quiz content -->


</body>
</html>

quiz/templates/correct_answer.html
{% load i18n %}
{% if previous.answers %}

  {% if user_was_incorrect %}
    <div class="alert alert-error">
  	  <strong>{% trans "You answered the above question incorrectly" %}</strong>
    </div>
  {% endif %}

  <table class="table table-striped table-bordered">
    <tbody>
  	  {% for answer in previous.answers %}
        {% if answer.correct %}
  	    <tr class="success">
  		  <td>{{ answer.content }}</td>
  		  <td><strong>{% trans "This is the correct answer" %}</strong></td>
        {% else %}
  		<tr>
      	  <td>{{ answer.content }}</td>
  		  <td>
  			{% if previous.question_type.MCQuestion %}
  			  {% if answer.id|add:"0" == previous.previous_answer|add:"0" %}
  			    {% trans "This was your answer." %}
  			  {% endif %}
  			{% endif %}
  		  </td>
  	  {% endif %}
  	    </tr>
  	{% endfor %}
    </tbody>
  </table>
{% endif %}

quiz/templates/progress.html
{% extends "quizbase.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {% trans "Progress Page" %} {% endblock %}
{% block description %} {% trans "User Progress Page" %} {% endblock %}

{% block content %}

  {% if cat_scores %}

  <h1>{% trans "Question Category Scores" %}</h1>

  <table class="table table-bordered table-striped">

	<thead>
	  <tr>
		<th>{% trans "Category" %}</th>
		<th>{% trans "Correctly answererd" %}</th>
		<th>{% trans "Incorrect" %}</th>
		<th>%</th>
	  </tr>
	</thead>

	<tbody>


	  {% for cat, value in cat_scores.items %}
	  <tr>
		<td>{{ cat }}</td>
		<td>{{ value.0 }}</td>
		<td>{{ value.1 }}</td>
		<td>{{ value.2 }}</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>


  {% endif %}

  {% if exams %}

  <hr>

  <h1>{% trans "Previous exam papers" %}</h1>
  <p class="lead">
	{% trans "Below are the results of exams that you have sat." %}
  </p>

  <table class="table table-bordered table-striped">

	<thead>
	  <tr>
		<th>{% trans "Quiz Title" %}</th>
		<th>{% trans "Score" %}</th>
		<th>{% trans "Possible Score" %}</th>
		<th>%</th>
	  </tr>
	</thead>

	<tbody>

	  {% for exam in exams %}

	  <tr>
		<td>{{ exam.quiz.title }}</td>
		<td>{{ exam.current_score }}</td>
		<td>{{ exam.get_max_score }}</td>
		<td>{{ exam.get_percent_correct }}</td>
	  </tr>

	  {% endfor %}

	</tbody>

  </table>

  {% endif %}


{% endblock %}

quiz/templates/question.html
{% extends "quizbase.html" %}
{% load i18n%}

{% load quiz_tags %}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}

<!--<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<div id="div1" style="display:none;">
hide
</div>

<script>
$(function() {
    setTimeout(function() {
            $('#div1').show();
    }, 1000);
});
</script>
<div><span id="timer" onclick="onClick()">{{quiz.time}}</span>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
function onClick(){
	$.ajax({
		url:"{% url 'lms:timer' %}",
		success: function(data) {
			// body...
			alert(data);
		}
	})
}
</script></div>"""-->
<div id="time">

</div>
<script type="text/javascript">
	function startTimer(duration, display) {
var timer = duration, minutes, seconds;
setInterval(function () {
    minutes = parseInt(timer / 60, 10)
    seconds = parseInt(timer % 60, 10);

    minutes = minutes < 10 ? "0" + minutes : minutes;
    seconds = seconds < 10 ? "0" + seconds : seconds;

    display.textContent = minutes + " " + " " + seconds;

    if (--timer < 0) {
        timer = duration;
    }
  console.log(parseInt(seconds))
  window.localStorage.setItem("seconds",seconds)
  window.localStorage.setItem("minutes",minutes)
}, 1000);
}

window.onload = function () {
  sec  = parseInt(window.localStorage.getItem("seconds"))
  min = parseInt(window.localStorage.getItem("minutes"))
 
  if(parseInt(min*sec)){
    var fiveMinutes = (parseInt(min*60)+sec);
  }else{
    var fiveMinutes = 60 * 5;
  }
    // var fiveMinutes = 60 * 5;
  display = document.querySelector('#time');
  startTimer(fiveMinutes, display);
};
</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">

setInterval(function() {
	//alert('halo')
	$.ajax({
		url:"{% url 'lms:timer' %}",
		data:{'hour':hour,'minute':minute,'seconds':seconds},
		success: function(data) {
			// body...
			alert(data);
		}
	})
}, 1000);
</script>

{% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>

  {% if previous.previous_outcome %}
	<div class="alert alert-success">
  {% else %}
	<div class="alert alert-warning">
  {% endif %}
  	  <p><small>
		{% trans "Your answer was" %} </small>
		<strong>
		  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
		</strong>
	  </p>

	</div>

	{% include 'correct_answer.html' %}

	<p><strong>{% trans "Explanation" %}:</strong></p>
	<div class="well " style="background-color: #fcf8e3;">
	  <p>{{ previous.previous_question.explanation }}</p>
	</div>

	<hr>

{% endif %}

<br />

{% if question %}

{% if progress %}
<div style="float: right;">
{% trans "Question" %} {{ progress.0|add:1 }} {% trans "of" %} {{ progress.1 }}
</div>
{% endif %}

<p>
  <small class="muted">{% trans "Question category" %}:</small>
  <strong>{{ question.category }}</strong>
</p>

<p class="lead">{{ question.content }}</p>

{% if question.figure %}
    <img src="{{ question.figure.url }}" alt="{{ question.content }}" />
{% endif %}

<form action="" method="POST">{% csrf_token %}
  <input type=hidden name="question_id" value="{{ question.id }}">

  <ul class="list-group">

	{% for answer in form.answers %}
	  <li class="list-group-item">
	    {{ answer }}
	  </li>
	{% endfor %}

  </ul>

  {% if progress.0|add:1 == progress.1 %}
    <input type="submit" value={% trans "Submit" %} class="btn btn-outline-success" style="width: 100px" >
  
    {% else %}
    <input type="submit" value={% trans "Next" %} class="btn btn-outline-success" style="width: 100px" >
    
    {% endif %}
    <input type="button" value="Reset" onClick="location.href=location.href" class="btn btn btn-outline-danger" style="width: 100px">
  
</form>

{% endif %}

<hr>


{% endblock %}

quiz/templates/result.html
{% extends "quizbase.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title}} {% endblock %}
{% block description %} {% trans "Exam Results for" %} {{ quiz.title }} {% endblock %}

{% block content %}

  {% if previous.answers %}

  <p class="muted"><small>{% trans "The previous question" %}:</small></p>
  <p>{{ previous.previous_question }}</p>
  <p>Your answer was
	<strong>
	  {{ previous.previous_outcome|yesno:"correct,incorrect" }}
	</strong>
  </p>
  {% include 'correct_answer.html' %}
  <p><strong>{% trans "Explanation" %}:</strong></p>
  <div class="well " style="background-color: #fcf8e3;">
    <p>{{ previous.previous_question.explanation }}</p>
  </div>
  <hr>

  {% endif %}

  {% if max_score %}

  <div>
	<h2>{% trans "Exam results" %}</h2>
	<p>
	  <small class="muted">{% trans "Exam title" %}: </small>
	  <strong>{{ quiz.title }}</strong></p>

	<p class="lead">
	  {% trans "You answered" %} {{ score }} {% trans "questions correctly out of" %} {{ max_score }}, {% trans "giving you" %} {{ percent }} {% trans "percent correct" %}
	</p>

	{% if quiz.pass_mark %}
	<hr>
        <p class="lead">{{ sitting.result_message }}</p>
	<hr>

	{% endif %}

	<p>{% trans "Review the questions below and try the exam again in the future"%}.</p>

	{% if user.is_authenticated %}

	  <p>{% trans "The result of this exam will be stored in your progress section so you can review and monitor your progression" %}.</p>

	{% endif %}
  </div>


  {% endif %}


  <hr>

  {% if possible %}

  <p class="lead">
	{% trans "Your session score is" %} {{ session }} {% trans "out of a possible" %} {{ possible }}
  </p>

  <hr>

  {% endif %}

  {% if questions %}

    {% for question in questions %}

      <p class="lead">
		{{ question.content }}
	  </p>

	  {% correct_answer_for_all question %}

      {% if question.user_answer %}
      <p>{% trans "Your answer" %}: {{ question|answer_choice_to_string:question.user_answer }}</p>
      {% endif %}

	  <p><strong>{% trans "Explanation" %}:</strong></p>
	  <div class="well " style="background-color: #fcf8e3;">
		<p>{{ question.explanation|safe }}</p>
	  </div>

	  <hr>

  {% endfor %}

  {% endif %}


{% endblock %}

quiz/templates/single_complete.html
{% extends "quizbase.html" %}
{% load i18n %}

{% load quiz_tags %}

{% block title %} {{ quiz.title }} {% endblock %}
{% block description %} {{ quiz.title }} - {{ quiz.description }} {% endblock %}

{% block content %}


{% if user.is_authenticated %}
  <p>{% trans "You have already sat this exam and only one sitting is permitted" %}.</p>
{% else %}
  <p>{% trans "This exam is only accessible to signed in users" %}.</p>
{% endif %}

{% endblock %}

quiz/templates/view_quiz_category.html
{% extends "quizbase.html" %}
{% load i18n %}
{% block title %}{% trans "Quizzes related to" %} {{ category.category }}{% endblock %}

{% block content %}
<h1>{% trans "Quizzes in the" %} <strong>{{ category.category }} </strong>{% trans "category" %}</h1>

  {% with object_list as quizzes %}
    {% if quizzes %}
        <ul>
        {% for quiz in quizzes %}
            <li>
			  <a href="{% url 'quiz_question' quiz_name=quiz.url %}">
				{{ quiz.title }}
			  </a>
			</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no quizzes" %}</p>
    {% endif %}
  {% endwith %}
{% endblock %}