authentication/urls.py
from authentication.views import profile,ProfileUpdate
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'authentication'

urlpatterns = [
    path('',profile,name = 'profile'),
    path('update/<slug:slug>/',ProfileUpdate.as_view(),name = 'update'),
    path('loginpop/', auth_views.LoginView.as_view(template_name='loginpop.html'),name = 'loginpop'),
]

forlms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('',include('lms.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/profile/', include('authentication.urls')),
    path('q/', include('quiz.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

lms/urls.py
from django.urls import path
from lms.views import index,about,blog,contact,event,cart,checkout,detail,onended,qna,allcourses,mycourses,\
CourseDetail,enrol,answer,timer
from authentication.views import profile

app_name = 'lms'

urlpatterns = [
    path('',index,name = 'index'),
    path('about/',about,name = 'about'),
    path('course/<slug:slug>/',CourseDetail.as_view(),name = 'coursedetail'),
    path('allcourses/',allcourses,name = 'allcourses'),
    path('qna/<slug:slug>/',qna,name = 'qna'),
    path('answer/<slug:slug>/<int:pk>/',answer,name = 'answer'),
    path('mycourses/',mycourses,name = 'mycourses'),
    path('blog/',blog,name = 'blog'),
    path('contact/',contact,name = 'contact'),
    path('event/',event,name = 'event'),
    path('cart/',cart,name = 'cart'),
    path('checkout/<slug:slug>/',checkout,name = 'checkout'),
    path('detail/<slug:slug>/',detail.as_view(),name = 'detail'),
    path('ajax/onended/',onended,name = 'onended'),
    path('ajax/staus/',enrol,name = 'status'),
    path('timer/',timer,name = 'timer'),
]

templates/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}

  <div class="form-group">
    <!--{{ field.label_tag }}-->

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

templates/bs4_form_label.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}

  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

templates/loginpop.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'auth_password_reset' %}">Lost password?</a></p>
<script>
    // Login Popup functionality     
    $('#loginBtn').on('click', function () {
        console.log("clicked");
        $('.modal-body').load("{% url 'authentication:loginpop' %}", function () {
            $('#myModal').modal({ show: true });
        });
    });
    // Register Popup functionality
    $('#registerBtn').on('click', function () {
        $('.modal-body').load("{% url 'registration_register' %}", function () {
            $('#myModal').modal({ show: true });
        });
    });
    $(function () {
        $('#loginModal').on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                url: "{% url 'authentication:loginpop' %}",
                type: 'POST',
                data: $('#loginModal').serialize(),
                success: function (data) {
                    window.location.href = "{% url 'lms:index' %}";
                    // alert('successfully submitted')
                }
            });
        });
    });
</script>

templates/profile.html
{% extends 'base.html' %}



{% block content %}


<section class="container mt-5">
  <div class="row details-form">

   <div class="col-md-4 myprofilebg">
 
<div class="nav flex-column nav-pills mb-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">

    
       <div class="text-center mt-5">
          <a href="{% url 'authentication:profile' %}">
        <img src="{{request.user.display_pic.url}}" class="img-fluid profileimg mb-3" alt="Responsive image" width="30%"></a>
           
</div>
    <div class="text-center">
  <div class="m-3">
  <a class="mybtn" href="{% url 'authentication:profile' %}"><i class="fas fa-user-circle"></i>&nbsp;&nbsp;My Profile</a>
  </div>

   <div class="m-3">
  <a class="mybtn" href="{% url 'lms:mycourses' %}"><i class="fa fa-book"></i>&nbsp;&nbsp;My Courses</a>
  </div>
   <div class="m-3">
  <a class="mybtn" href="{% url 'authentication:update' request.user.slug %}"><i class="fas fa-edit"></i>&nbsp;&nbsp;Edit / Update</a>
  </div>
  </div>
</div>
</div>
 <div class="col-md-8">

<div class="tab-content" id="v-pills-tabContent">
  <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">

<table class="table mt-5">
  <thead>
    
  
  </thead>
  <tbody>
   
      <th scope="row">username</th>
      <td>{{request.user.username}}</td>
     
    
    </tr>
    <tr>
      <th scope="row">First Name</th>
      <td>{{request.user.first_name}}</td>
    
    </tr>
     <tr>
      <th scope="row">Last Name</th>
      <td>{{request.user.last_name}}</td>
    
    </tr>
     <tr>
      <th scope="row">College</th>
      <td>{{request.user.college}}</td>
    
    </tr>
     <tr>
      <th scope="row">Branch</th>
      <td>{{request.user.branch}}</td>
    
    </tr>
    
    <tr>
      <th scope="row">Email</th>
      <td>{{request.user.email}}</td>
      
    </tr>
    <tr>
      <th scope="row">Phone Number</th>
      <td>{{request.user.mobile}}</td>
      
    </tr>
    
   
  </tbody>
</table>

  </div>
  <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
  </div>
  <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
 



  </div>
</div>
</div>
</div>
</section>


{% endblock %}

templates/quizbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>lms</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link
    href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400;0,700;1,400;1,700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="{%static 'sass/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{%static 'sass/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{%static 'sass/slick.css' %}">
  <link rel="stylesheet" href="{%static 'sass/slick-theme.css' %}">

  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link rel="stylesheet" href="{% static 'profile/edit_profile.css' %}">

  {% endblock %}
</head>

<body>



<section class="container mt-4">
  {% block content %}

  {% endblock %}
</section>
  <!--footer-->
 
  <!-- Login Modal -->


  <!-- script  -->
  <script src="https://kit.fontawesome.com/a01bd6bffe.js" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  <script src="{%static 'js/owl.carousel.min.js' %}"></script>
  <script src="{%static 'js/home-page.js' %}"></script>


</body>

</html>

templates/updateprofile.html
{% extends "registration/registration_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "" %}{% endblock %}

{% block content %}
 <section class="container mt-5">
 <div class="row details-form">
    
      <div class="col-md-6">
     
<form class="p-3 p-lg-4" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
     {% include 'bs4_form_label.html' with form=form %}
    <input class="btn  btn-primary btn-block form-button" type="submit" value="{% trans 'Update' %}" />
    <input class="btn  btn-primary btn-block form-button" type="hidden" name="next" value="{{ next }}" />
    
  
</form>


  </div>
     <div class="col-md-6 regbg text-center">
        <h3 class="logintext">Edit Profile</h3>
        <img class="regimg" src="{% static 'img/edit001.png' %}" class="img-fluid"
            alt="Responsive image">
           <p class="editpar mt-3">
Lorem ipsum gravida nibh vel velit auctor aliquetnean sollicitudin, lorem quis bibendum auci elit consequat is simply free text available in the psutis sem nibh id eis sed odio sit amet.Lorem ipsum gravida nibh vel velit auctor aliquetnean sollicitudin.</p>
      </div>
  </div>
  </section>
{% endblock %}


{% comment %}

{% endcomment %}