authentication/urls.py
from authentication.views import profile,ProfileUpdate
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'authentication'

urlpatterns = [
    path('',profile,name = 'profile'),
    path('update/<slug:slug>/',ProfileUpdate.as_view(),name = 'update'),
    path('loginpop/', auth_views.LoginView.as_view(template_name='loginpop.html'),name = 'loginpop'),
]

forlms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('',include('lms.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('accounts/profile/', include('authentication.urls')),
    path('q/', include('quiz.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

lms/urls.py
from django.urls import path
from lms.views import index,about,blog,contact,event,cart,checkout,detail,onended,qna,allcourses,mycourses,\
CourseDetail,enrol,answer,timer
from authentication.views import profile

app_name = 'lms'

urlpatterns = [
    path('',index,name = 'index'),
    path('about/',about,name = 'about'),
    path('course/<slug:slug>/',CourseDetail.as_view(),name = 'coursedetail'),
    path('allcourses/',allcourses,name = 'allcourses'),
    path('qna/<slug:slug>/',qna,name = 'qna'),
    path('answer/<slug:slug>/<int:pk>/',answer,name = 'answer'),
    path('mycourses/',mycourses,name = 'mycourses'),
    path('blog/',blog,name = 'blog'),
    path('contact/',contact,name = 'contact'),
    path('event/',event,name = 'event'),
    path('cart/',cart,name = 'cart'),
    path('checkout/<slug:slug>/',checkout,name = 'checkout'),
    path('detail/<slug:slug>/',detail.as_view(),name = 'detail'),
    path('ajax/onended/',onended,name = 'onended'),
    path('ajax/staus/',enrol,name = 'status'),
    path('timer/',timer,name = 'timer'),
]

lms/models.py
from django.db import models
from authentication.models import MyUser
from lms.ytd import ytapi,minsec
import itertools,random
from django.utils.text import slugify
from quiz.models import Quiz

# Create your models here.

class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(MyUser,on_delete = models.CASCADE,null = True)

	class Meta:
		abstract = True

class Category(models.Model):
	category = models.CharField(max_length = 200)
	img380x256 = models.ImageField(upload_to = '',default = 'market.jpg')

	def __str__(self):
		return self.category

	def trending_courses(self):
		objects = [i for i in Course.objects.all()]
		random.shuffle(objects)
		return objects[:8]

class Project(models.Model):
	title = models.CharField(max_length = 100)
	description = models.TextField()

	def __str__(self):
		return self.title

class Trainer(models.Model):
	name = models.CharField(max_length = 100)
	image = models.ImageField(upload_to = '',default = 'market.jpg')
	about = models.CharField(max_length = 200)
	description = models.TextField()
	linkedin = models.URLField()
	quora = models.URLField()

	def __str__(self):
		return self.name

class FAQ(models.Model):
	question = models.CharField(max_length = 300)
	answer = models.TextField()

	def __str__(self):
		return self.question


class Course(models.Model):
	title = models.CharField(max_length = 100)
	category = models.ForeignKey(Category, on_delete = models.CASCADE)
	short_description = models.TextField()
	description = models.TextField()
	video_id = models.CharField(max_length = 20,default = 'bY6m6_IIN94',verbose_name = "Introduction Video ID")
	img1240x600 = models.ImageField(upload_to = '')
	img293x274 = models.ImageField(upload_to = '')
	duration = models.CharField(max_length = 10)
	credits = models.IntegerField()
	reviews = models.FloatField(verbose_name = 'rating')
	enrolled = models.IntegerField()
	slug = models.SlugField()
	offer_price = models.IntegerField()
	original_price = models.IntegerField()
	tags = models.TextField(verbose_name = 'Key Skills')
	trainer = models.ForeignKey(Trainer, on_delete = models.CASCADE)
	project = models.ManyToManyField(Project)
	faq = models.ManyToManyField(FAQ)


	def __str__(self):
		return self.title

	def get_tags(self):
		return self.tags.split(",")

	def lesson_count(self):
		lesson_list = [i.lesson_set.all().count() for i in Course.objects.get(id = self.id).module_set.all()]
		return list(itertools.accumulate(lesson_list))[-1]



class Module(models.Model):
	course = models.ForeignKey(Course,on_delete = models.CASCADE)
	module = models.CharField(max_length = 1000)
	pdf = models.FileField(upload_to = '',default = 'mozilla.pdf',blank = True,null = True)
	quiz = models.ForeignKey(Quiz,on_delete = models.CASCADE,blank = True,null = True)
	
	def __str__(self):
		return self.module

	def duration(self):
		obj = Module.objects.get(id = self.id)
		videos = [ytapi(i.video_id) for i in obj.lesson_set.all()]
		return minsec(list(itertools.accumulate(videos))[-1])


class Lesson(models.Model):
	module = models.ForeignKey(Module,on_delete = models.CASCADE)
	lesson = models.CharField(max_length = 1000)
	pdf = models.FileField(upload_to = '',default = 'mozilla.pdf',blank = True,null = True)
	video_id = models.CharField(max_length = 11)
	preview = models.BooleanField(default = False,verbose_name = "Show Preview")

	def __str__(self):
		return self.lesson

	def duration(self):
		return minsec(ytapi(self.video_id))

	def get_slug(self):
		return slugify(self.lesson,allow_unicode = True)

	def all_lessons(self):
		return Lesson.objects.all().count()


class CourseStatus(models.Model):
	course = models.ForeignKey(Course,on_delete = models.CASCADE)
	user = models.ForeignKey(MyUser,on_delete = models.CASCADE)
	completed_lessons = models.ManyToManyField(Lesson,related_name = 'completed_lessons',blank = True)
	current_lesson = models.ForeignKey(Lesson,on_delete = models.CASCADE, related_name = 'current_lesson',blank = True,null = True)

	class Meta:
		verbose_name_plural = "Course Status"


class Question(TimeStamp):
	question = models.TextField()
	course = models.ForeignKey(Course,on_delete = models.CASCADE)

	def __str__(self):
		return self.question

class Answer(TimeStamp):
	question = models.ForeignKey(Question,on_delete = models.CASCADE,related_name = "answers")
	answer = models.TextField()

	def __str__(self):
		return self.answer

lms/forms.py
from django import forms
from lms.models import Question,Answer

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['question']

class AnswerForm(forms.ModelForm):
	class Meta:
		model = Answer
		fields = ['answer']

lms/views.py
from django.shortcuts import render,reverse
from lms.models import Course,Module,Lesson,CourseStatus,Category,Question,Answer
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.http import HttpResponseRedirect,JsonResponse
from django.views.generic.edit import FormMixin
from lms.forms import QuestionForm,AnswerForm
import time
from codetiming import Timer

# Create your views here.

def index(request):
	category = Category.objects.all()
	return render(request,'index.html',{'category':category})

def about(request):
	return render(request,'about-us.html')

def qna(request,slug):
	course = Course.objects.get(slug = slug)
	course_id = course.id
	course_title = course.title
	course_slug = course.slug
	questions = Question.objects.filter(course_id = course_id)
	return render(request,'qna.html',{'questions':questions,'course':course_slug,'course_title':course_title,'aform':AnswerForm()})

class CourseDetail(DetailView):
	model = Course
	template_name = 'course.html'

def blog(request):
	return render(request,'blog.html')

def contact(request):
	return render(request,'contact.html')

def event(request):
	return render(request,'event.html')

def allcourses(request):

	return render(request,'all-courses.html')

def mycourses(request):
	mycourses = CourseStatus.objects.filter(user = request.user)
	return render(request,'mycourses.html',{'mycourses':mycourses})

def cart(request):
	return render(request,'cart.html')

def checkout(request,slug):
    return render(request,'checkout.html')

def answer(request,slug,pk):
	if request.method == 'POST':
		answer = request.POST.get('answer')
		obj = Answer(question_id = pk,answer = answer,user = request.user)
		obj.save()
	return HttpResponseRedirect(reverse('lms:qna', kwargs = {'slug':slug}))


class detail(FormMixin, DetailView):
	model = Course
	template_name = 'purchased-course.html'
	form_class = QuestionForm

	def get_success_url(self):
		return reverse('lms:detail', kwargs={'slug': self.object.slug})

	def get_context_data(self, **kwargs):
		context = super(detail, self).get_context_data(**kwargs)
		is_enrolled = self.request.user.is_authenticated and CourseStatus.objects.filter(user = self.request.user).filter(course = kwargs['object']).exists()
		if is_enrolled:
			user_course_it = CourseStatus.objects.filter(user = self.request.user).filter(course = kwargs['object'])
			user_course = CourseStatus.objects.get(id = [i.id for i in user_course_it][0])
			context['form'] = QuestionForm()
			context['aform'] = AnswerForm()
			context['questions'] = Question.objects.filter(course = kwargs['object'])

		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		course = Course.objects.get(slug = kwargs['slug'])
		form = self.get_form()
		question = request.POST.get('question')
		if form.is_valid():
			form.instance.user = self.request.user
			form.instance.course = course
			form.instance.question = question
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		form.save()
		return super(detail, self).form_valid(form)

def onended(request):
	if request.is_ajax():
		iframe_id = request.GET.get('iframe_id')
		status = CourseStatus.objects.get(user = request.user)
		current_lesson = Lesson.objects.get(video_id = iframe_id)
		status.current_lesson = current_lesson
		status.completed_lessons.add(current_lesson)
		count = len([i for i in status.completed_lessons.all() if i in current_lesson.module.lesson_set.all()])
		data = {'count':count,'module':current_lesson.module.id,'lesson':current_lesson.id}
	return JsonResponse(data)

def enrol(request):
	if request.is_ajax():
		username = request.GET.get('username')[0]
		data = request.GET.get('status')
		#print(data)
		r = data.split(':')
		slug = r[0]
		payment_id = r[1]
		enrol,created = CourseStatus.objects.get_or_create(user_id = request.user.id,course_id = Course.objects.get(slug = slug).id)
		data = {'slug':slug,'created':created}
		return JsonResponse(data)

def navbar(request):
   return {'category':Category.objects.all()}

def timer(request):
	if request.is_ajax():
		hour = request.GET.get('hour')
		minute = request.GET.get('minute')
		seconds = request.GET.get('seconds')
		total_seconds = ((hour*60)+minute)*60 + seconds
		t = Timer(name = request.user)
		t.start()
		time.sleep(1)
		t.stop()
		elapsed_time = t.stop()
		return

lms/templates/nav.html
{% load static %}

<!-- Menu Items  -->
<header id="headerSection" class="sticky-top">
  <!-- Top Menu  -->

  <div class="container-fluid py-1 sticky-top" id="imgMenu">

    <a href="{% url 'lms:index' %}"> <img src="{% static 'img/headlogo.jpg' %}" class="w-100 d-none d-sm-block"></a>
    <a href="{% url 'lms:index' %}"> <img src="{% static 'img/mobilehead.jpg' %}" class="w-100 d-block d-sm-none"></a>
  </div>

  <!-- Secondary Mobile Menu  -->
  <nav class="navbar sticky-top mobile-menu-height align-items-center" id="mobileMenu">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobileMenuItems"
      aria-controls="mobileMenuItems" aria-expanded="false" aria-lable="Toggle Navigation">
      <span class=""><i class="fas fa-bars fa-1x"></i></span>
    </button>
    <div class="" id="searchBarMobile">
      <div class="input-group" id="searchGroup">
        <input type="text" class="form-control" placeholder="Search.." aria-label="Search"
          aria-describedby="searchIcon">
        <div class="input-group-append">
          <span class="input-group-text" id="searchIcon">
            <i class="fas fa-search"></i>
          </span>
        </div>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="mobileMenuItems">
      <ul class="navbar-nav">
        <li class="nav-item active"> <a class="nav-link" href="#">Home </a> </li>
        <li class="nav-item"><a class="nav-link" href="#"> About </a></li>
        <li class="nav-item"><a class="nav-link" href="#"> Services </a></li>
        <li class="nav-item dropdown">
          <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown"> More items </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#"> Submenu item 1</a></li>
            <li><a class="dropdown-item" href="#"> Submenu item 2 </a></li>
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><a class="nav-link" href="#"> Menu item </a></li>
        <li class="nav-item"><a class="nav-link" href="#"> Menu item </a></li>
        <li class="nav-item dropdown">
          <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown"> Dropdown right </a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><a class="dropdown-item" href="#"> Submenu item 1</a></li>
            <li><a class="dropdown-item" href="#"> Submenu item 2 </a></li>
          </ul>
        </li>

      </ul>
    </div>
  </nav>
  <!-- Secondary Menu  -->
  <nav class="navbar navbar-expand-lg navbar-dark  main-menu" id="desktopMenu">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
      aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarTogglerDemo01">

      <div class="dropdown">
        <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <img src="{% static 'img/cat01.png' %}" class="img-fluid" alt="Responsive image">&nbsp;&nbsp;Categories
        </a>
        <ul class="dropdown-menu multi-level mt-2" role="menu" aria-labelledby="dropdownMenu">
          {% for i in category %}


          <li class="dropdown-submenu">
            <a class="dropdown-item" tabindex="-1" href="#">{{i.category}}</a>
            <ul class="dropdown-menu">
              {% for j in i.course_set.all %}
              <li class="dropdown-item"><a tabindex="-1" href="{% url 'lms:coursedetail' j.slug %}">{{j.title}}</a>
              </li>
              {% endfor %}
            </ul>
          </li>
          {% endfor %}
        </ul>
      </div>


      <form class="form-inline pad" action = "{% url 'lms:allcourses' %}" method ='POST' value='{{request.POST.q}}'>
        {% csrf_token %}
        <div class="input-group">

          &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" class="form-control mysearch" name = 'q' value = '{{request.POST.q}}' placeholder="What do you want to learn ?" aria-label="Username" aria-describedby="basic-addon1">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1" type="submit"><i class="fa fa-search" style="font-size:20px"></i></span>
          </div>
        </div>
      </form>

      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'lms:index' %}">Home<span class="sr-only"></span></a>
        </li>


      </ul>
      <i class="fa fa-shopping-cart" style="font-size:28px;color:white"></i>&nbsp;&nbsp;

      <form class="form-inline my-2 my-lg-0">
        {% if not user.is_authenticated %}
        
	<a href="{% url 'auth_login' %}" class="btn btn-outline-primary  login-btn my-2 my-sm-0" type="submit" id="">Login</a>
        <!-- <a href="#myModal" class="btn btn-outline-primary login-btn my-2 my-sm-0" type="submit"  data-remote="{% url 'auth_login' %}" data-toggle="modal" data-target="#myModal">Login</a> -->
        <!-- <a data-url="{% url 'auth_login' %}" class="btn btn-outline-primary login-btn my-2 my-sm-0" type="submit" id="loginBtn">Login</a> -->
        <!-- <button class="btn btn-primary btn-action" data-url="{% url 'auth_login' %}" id="loginBtn">Login</button> -->
        &nbsp;&nbsp;

        <a href="{% url 'registration_register' %}" class="btn btn-outline-primary  login-btn my-2 my-sm-0" type="submit" id="">Register</a>
        {% else %}
        <span class="myprofile">{{request.user}}</span><a href="{% url 'auth_logout' %}"
          class="btn btn-outline-primary  login-btn my-2 my-sm-0" type="submit">Logout</a>&nbsp;&nbsp;<a
          href="{% url 'authentication:profile' %}"><i class="fa fa-user-circle-o"
            style="font-size:28px;color:white"></i></a>
        {% endif %}
      </form>
    </div>
  </nav>
</header>

lms/templates/qna.html
{% extends 'base.html' %}
{% load static %}
{% block head %}


<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Questions and Answers</title>

<link rel="stylesheet" href="{% static 'style.css' %}">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<link
  href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400;0,700;1,400;1,700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  rel="stylesheet">
  
{% endblock %}



{% block content %}

<section>
  <div class="container">
<h5 class="text-center m-4">{{course_title}}</h5>
<div class="row mt-5 ml-2">
          <div class="col-md-12">
            <h6 class="mb-3">{{questions.count}} questions in {{course_title}}
            </h6>
            <hr>
            <!-- Questions  -->
            {% for i in questions %}
            <div class="row mt-2 no-gutters">
              <div class="col-md-1">
                <img class="heroImg" src="{{i.user.display_pic.url}}" width="50px">
              </div>
              <div class="col-md-8">
                <h6> {{i.question}}</h6>
                <p>{{i.user}} · {{i.created_at}}</p>
                {% for j in i.answers.all %}
                <p> <img class="heroImg" src="{{j.user.display_pic.url}}" width="50px"> &nbsp;&nbsp;{{j.answer}}
                </p>

                <p>{{j.user}} · {{j.created_at}}</p>
                {% endfor %}

              </div>
              <div class="col-md-3">
                <a href="#" data-toggle="modal" data-target="#answerFormModal{{i.pk}}">Answer this question</a>
              </div>
            </div>
              <div class="modal fade" id="answerFormModal{{i.pk}}" tabindex="-1" role="dialog" aria-labelledby="answerFormModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-center" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="answerFormModalLabel">
                        {{i.question}}
                      </h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <form action="{% url 'lms:answer' course i.pk %}" method="post" >
                        <div class="form-group">
                          {% csrf_token %}
                          {% include 'bs4_form_label.html' with form=aform %}
                    </div>
                    <div class="modal-footer">
                      <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                  </form>
                  </div>
                </div>
              </div>

            </div>
            {% endfor %}


           
          </div>
        </div>
      </div>
        </section>
        {% endblock %}

lms/templates/regnav.html
{% load static %}

<header id="headerSection" class="sticky-top">
    <!-- Top Menu  -->

    <div class="container-fluid py-1">

        <a href="{% url 'lms:index' %}"> <img src="{% static 'img/headlogo.jpg' %}" class="w-100 d-none d-sm-block"></a>
        <a href="{% url 'lms:index' %}"> <img src="{% static 'img/mobilehead.jpg' %}"
                class="w-100 d-block d-sm-none"></a>
    </div>

    <!-- Secondary Mobile Menu  -->
    <nav class="navbar sticky-top mobile-menu-height d-flex flex-row no-gutters align-items-center justify-content-between"
        id="mobileMenu">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobileMenuItems"
            aria-controls="mobileMenuItems" aria-expanded="false" aria-lable="Toggle Navigation">
            <span class=""><i class="fas fa-bars fa-1x"></i></span>
        </button>
        <div class="" id="searchBarMobile">
            <div class="input-group" id="searchGroup">
                <input type="text" class="form-control" placeholder="Search.." aria-label="Search"
                    aria-describedby="searchIcon">
                <div class="input-group-append">
                    <span class="input-group-text" id="searchIcon">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
            </div>
        </div>
        <div class="collapse navbar-collapse py-3" id="mobileMenuItems">
            <h5>Hi, {{request.user.username}}</h5>
            <hr>
            <ul class="navbar-nav">
                <li class="nav-item active"> <a class="nav-link" href="/mycourses.html">My Courses </a>
                </li>
                <li class="nav-item active"> <a class="nav-link" href="/mycourses.html">My Cart</a>
                </li>
                <li class="nav-item active"> <a class="nav-link" href="/mycourses.html">Profile</a>
                </li>
                <li class="nav-item active"> <a class="nav-link" href="/mycourses.html">Settings</a>
                </li>
                <li class="nav-item active"> <a class="nav-link" href="/index.html">Home </a> </li>
                <li class="nav-item"><a class="nav-link" href="#"> About </a></li>
                <li class="nav-item"><a class="nav-link" href="/all-courses.html"> Courses </a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">Category 1</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="course.html"> Course 1</a></li>
                        <li><a class="dropdown-item" href="course.html"> Course 2 </a></li>
                    </ul>
                </li>
                <hr>
                <li class="nav-item active"> <a class="nav-link" href="/index.html">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Secondary Menu  -->
    <nav class="navbar navbar-expand-lg navbar-dark  main-menu" id="desktopMenu">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarTogglerDemo01">

            <div class="dropdown">
                <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <img src="{% static 'img/cat01.png' %}" class="img-fluid"
                        alt="Responsive image">&nbsp;&nbsp;Categories
                </a>
                <ul class="dropdown-menu multi-level mt-2" role="menu" aria-labelledby="dropdownMenu">
                    {% for i in category %}


                    <li class="dropdown-submenu">
                        <a class="dropdown-item" tabindex="-1" href="#">{{i.category}}</a>
                        <ul class="dropdown-menu">
                            {% for j in i.course_set.all %}
                            <li class="dropdown-item"><a tabindex="-1"
                                    href="{% url 'lms:coursedetail' j.slug %}">{{j.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>


            <form class="form-inline pad" action="{% url 'lms:allcourses' %}" method='POST' value='{{request.POST.q}}'>
                {% csrf_token %}
                <div class="input-group">

                    &nbsp;&nbsp;&nbsp;&nbsp;<input type="text" class="form-control mysearch" name='q'
                        value='{{request.POST.q}}' placeholder="What do you want to learn ?" aria-label="Username"
                        aria-describedby="basic-addon1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1" type="submit"><i class="fa fa-search"
                                style="font-size:20px"></i></span>
                    </div>
                </div>
            </form>

            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'lms:index' %}">Home<span class="sr-only"></span></a>
                </li>


            </ul>
            <i class="fa fa-shopping-cart" style="font-size:28px;color:white"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="dropdown" id="desktopProfile">

                <a href="" class="dropdown show" id="profileMenu" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="profile-icon">
                        <h5 class="m-0">{{request.user.username|slice:'1'}}</h5>
                    </div>
                </a>
                <div class="dropdown-menu profile-menu-items" aria-labelledby="profileMenu">
                    <a href="{% url 'authentication:profile' %}" class="dropdown-item"><span
                            style="color: #ff9f00;">{{request.user.username}}</span></a>
                    <a href="{% url 'lms:mycourses' %}" class="dropdown-item">My Courses</a>
                    <a href="#" class="dropdown-item">My Cart</a>
                    <a href="{% url 'authentication:profile' %}" class="dropdown-item">Profile</a>
                    <a href="{% url 'authentication:update' request.user.slug %}" class="dropdown-item">Edit Profile</a>
                    <hr>
                    <a href="{% url 'auth_logout' %}" class="dropdown-item">Log Out</a>
                </div>
            </div>

        </div>
    </nav>
</header>